circle.yml
=> Add CircleCI config

app/views/people/_form_basics.haml
Thanks to @davidhan527 for finding this one!
=> Remove extra family fields from person edit form

app/views/groups/_details.haml, config/locales/en/groups.yml
This is my first go at fixing a bug so please go gentle if I haven't got this merge request thing sorted :)
=> Add directions to group details partial

app/models/family.rb, app/models/group.rb, config/application.rb, config/secrets.yml.example, spec/support/geocoder.rb
=> Improve geocoding functionality to remove long/lats

app/models/concerns/geocode.rb, app/models/family.rb, app/models/group.rb, spec/models/family_spec.rb, spec/models/group_spec.rb
=> Refactor geocoding

app/models/person.rb
I made changes to git rid of a bunch of Rubocop complaints in this file.
* Changed `and`/`or` to `&&`/`||`
* Broke up long lines
* Used `%r{ }` for regexes containing slashes
* Aligned method call args
* Broke up methods that had too many lines
Probably some other stuff I can't remember
=> Clean up coding style on Person model

app/assets/javascripts/app/search.js.coffee, app/models/search.rb, app/views/searches/create.html.haml, config/locales/en/search.yml, spec/models/search_spec.rb
Tidied up the text a bit, but apart from that as per previous pull request where I asked for comments on the code
=> Ability to search based on membership of groups with a selected category

app/controllers/administration/admins_controller.rb, app/models/admin.rb, app/models/concerns/person/administrator.rb, app/models/person.rb, spec/models/person_spec.rb
This PR fixes #411 and supersedes #412.
=> Don't allow orphaned admins in the first place

.watchr, app/controllers/generated_files_controller.rb, app/controllers/groups_controller.rb, app/controllers/people_controller.rb, app/controllers/printable_directories_controller.rb, app/jobs/export_job.rb, app/jobs/printable_directory_job.rb, app/models/concerns/person/export.rb, app/models/generated_file.rb, app/models/group.rb, app/views/generated_files/show.html.haml, app/views/generated_files/show.js.erb, db/migrate/20150206035943_change_generated_files.rb, db/schema.rb, spec/jobs/export_job_spec.rb
=> Use ActiveJob for more stuff

app/helpers/application_helper.rb, spec/models/person_spec.rb
=> Fix printed directory pdf generation

app/assets/stylesheets/app/timeline.css.scss, app/controllers/application_controller.rb, app/controllers/groups_controller.rb, app/controllers/streams_controller.rb, app/decorators/stream_item_decorator.rb, app/helpers/groups_helper.rb, app/helpers/streams_helper.rb, app/models/group.rb, app/models/person.rb, app/views/groups/index.html.haml, config/locales/en/general.yml, db/migrate/20150308223312_add_last_seen_items_to_people.rb, db/schema.rb
=> Show "new" badges on items that are actually new

build/packer.json, build/ubuntu/14.04/provision.sh
=> Add XSendFile to provision, rebuild AMI and Virtual Appliance

app/assets/stylesheets/app/forms.css.scss, app/controllers/administration/checkin/groups_controller.rb, app/models/group.rb, app/views/groups/_form_features.haml, config/locales/en/general.yml, config/locales/en/groups.yml, spec/factories/checkin_times.rb, spec/models/group_spec.rb
=> Force attendance enabled for groups used by check-in

.rubocop.yml, app/assets/javascripts/app/timeline.js.coffee, app/controllers/groups_controller.rb, app/controllers/people_controller.rb, app/controllers/printable_directories_controller.rb, app/controllers/streams_controller.rb, app/decorators/stream_item_decorator.rb, app/jobs/export_job.rb, app/jobs/message_send_job.rb, app/jobs/printable_directory_job.rb, app/jobs/stream_item_group_job.rb, app/models/concerns/person/streamable.rb, app/models/group.rb, app/models/message.rb, app/models/person.rb, app/models/site.rb, app/models/stream_item.rb, config/locales/en/stream.yml, db/migrate/20150316001718_remove_false_from_stream_items.rb, db/migrate/20150316002056_add_stream_item_group_id_to_stream_items.rb, db/schema.rb, spec/jobs/export_job_spec.rb, spec/jobs/stream_item_group_job_spec.rb, spec/models/person_spec.rb, spec/rails_helper.rb
=> Group like stream items

app/models/notifier.rb, spec/models/notifier_spec.rb
=> Fix incoming email using email_host

app/assets/javascripts/app/documents.js.coffee, app/assets/stylesheets/app/documents.css.scss, app/assets/stylesheets/app/tables.css.scss, app/authorizers/attachment_authorizer.rb, app/authorizers/document_authorizer.rb, app/authorizers/document_folder_authorizer.rb, app/controllers/attachments_controller.rb, app/controllers/documents_controller.rb, app/helpers/groups_helper.rb, app/helpers/streams_helper.rb, app/models/document.rb, app/models/document_folder.rb, app/models/document_folder_group.rb, app/models/group.rb, app/views/documents/_folder_form.haml, app/views/documents/index.html.haml, app/views/documents/show.html.haml, app/views/groups/_details.haml, app/views/groups/_select_group.haml, config/locales/en/documents.yml, config/locales/en/general.yml, config/routes.rb, db/migrate/20150318034613_create_document_folder_groups.rb, db/schema.rb, lib/tasks/migrate_group_attachments.rake, spec/controllers/attachments_controller_spec.rb, spec/controllers/documents_controller_spec.rb, spec/models/authorizers/attachment_authorizer_spec.rb, spec/models/document_folder_spec.rb, spec/models/document_spec.rb
=> Allow restricting document folders by group

app/assets/javascripts/app/admin.js.coffee, app/assets/javascripts/app/sparklines.js.coffee.erb, app/assets/javascripts/application.js.coffee, app/assets/stylesheets/app/admin.css.scss, app/assets/stylesheets/app/sparklines.css.scss, app/models/search.rb, app/presenters/stats/attendance_graph_presenter.rb, app/views/administration/checkin/dashboards/show.html.haml, app/views/administration/dashboards/show.html.haml, config/locales/en/admin.yml, spec/presenters/checkin_presenter_spec.rb, spec/presenters/stats/attendance_graph_presenter_spec.rb, vendor/assets/javascripts/jquery.sparkline.js
=> Better dashboard

Gemfile
modified gem source path with https and locked the rails version with latest stable
=> Added https and locked rails version for latest stable

config/initializers/email.rb, spec/models/person_spec.rb
so emails on new TLDs can be accepted.
Resolves #290 
Please ignore/close this PR if this is something you're working on.  I'm new to the project and would like to find ways to contribute.  This issue seems to be a good first step. :)
=> Relax the email validation rule

app/assets/javascripts/application.js.coffee, app/views/messages/_form.html.haml, vendor/assets/javascripts/bootstrap-filestyle.js
=> Add bootstrap-filestyle plugin to style the file upload button

Vagrantfile
Modifying Apache virtualhost entry to use current ruby version.
=> Vagrantfile updates.

app/views/layouts/_navbar_right.haml
=> Fix logged-in user icon.

app/models/site.rb, spec/models/site_spec.rb
=> Fix links in emails not using https://

app/reports/group_contact_details_report.rb, app/reports/weekly_attendance_report.rb
=> Fix reports since upgrade to Dossier gem

app/models/concerns/person/pdf_gen.rb
=> Fix printed directory when family image is a PNG

app/controllers/tags_controller.rb
Hello. Just a minor change, which uses more intention revealing methods to get rid of the exception raise.
=> Simplify the TagsController

app/controllers/administration/imports_controller.rb
=> Eager load associations for the Import model (fixes n + 1 query problem)

app/assets/javascripts/app/tabs.js.coffee
Comments and feedback always welcome!
The one remaining bug that I see with this is:
Click through the tabs, then use the back button, the previously selected tab stays grey until clicking anywhere on the page.
=> Changing tabs then clicking Back does not work #552

app/views/people/_details.haml, config/locales/en/people.yml
=> Add 'About' section to user profile view

app/views/messages/show.html.haml
=> fixed bug #601 'User photo is blurry when viewing a message'

app/models/family.rb
In order to fix this problem, I added a few more conditions to the raw SQL query that creates the data sent to the map.
=> fix for bug #596 'Map Display Reveals Private Address Information'

app/helpers/people_helper.rb, app/models/person.rb, app/models/search.rb, app/models/updater.rb, app/views/people/_form_basics.haml, app/views/searches/_results.haml, config/locales/en/general.yml, db/migrate/20160403231924_add_alias_to_person.rb, db/schema.rb, spec/controllers/searches_controller_spec.rb, spec/models/person_spec.rb
updated directory and show person views
Fixes #257
=> Added alias to person, name_and_nick display method,

app/models/family.rb, config/locales/cs/families.yml
In Czech, wife's and family name are usualy extensions of husband's name.
I'm not sure if you will like this, making code changes based on locale, but... what could go wrong?
=> Propose specific form of family name for Czech.

config/locales/cs/admin.yml, config/locales/cs/attendance.yml, config/locales/cs/checkin.yml, config/locales/cs/documents.yml, config/locales/cs/families.yml, config/locales/cs/general.yml, config/locales/cs/groups.yml, config/locales/cs/import.yml, config/locales/cs/reports.yml, config/locales/cs/search.yml, config/locales/cs/stream.yml, config/locales/cs/tasks.yml, config/locales/cs/verses.yml
Once the extended pluralization is supported, languages which
count on it need to provide "few" key everywhere.
=> Added "few" pluralization forms to Czech texts.

config/locales/cs/memberships.yml, config/locales/cs/messages.yml
Do not merge yet, I'll add some more files...
=> Another bunch of texts translated to Czech

Gemfile, Gemfile.lock, app/models/person.rb, app/views/administration/settings/index.html.haml, config/settings.yml, spec/controllers/accounts_controller_spec.rb
* Added setting to change the required password length
* Added setting to require a strong password using the strong-password gem
=> Issue #600 added settings to require stronger passwords

app/authorizers/album_authorizer.rb
Hi.
I replaced ```and``` operator with ```&&``` since ```and``` has lower precedence than ```&&```. This carries a major bug risk. 
Thank you.
=> Reformat album_authorizers.rb

config/locales/cs/people.yml, config/locales/cs/search.yml
Do not merge yet, I hope I'll add more translation shortly
=> Fix Czech translation of 'Elder'

app/authorizers/attachment_authorizer.rb
Hello.
Looks like there was a control flow operator (and) in file app/authorizers/attachment_authorizer.rb.
To mitigate the bug risk, I replaced it with boolean operator &&. 
Thank you.
=> Replaced control flow operator with boolean operator

app/assets/javascripts/app/messages.js.coffee, app/controllers/messages_controller.rb, app/models/message.rb, app/views/messages/_form.html.haml, app/views/messages/new.html.haml, app/views/messages/new.js.erb, config/locales/en/messages.yml, spec/controllers/messages_controller_spec.rb, spec/models/message_spec.rb
(separate private message for each member selected)
=> Feature send to subset of group

app/controllers/streams_controller.rb, app/views/administration/settings/index.html.haml, config/locales/en/admin.yml, config/settings.yml, spec/controllers/streams_controller_spec.rb
=> Setting for disabling stream for homepage

app.yml
=> We don't need NOPASSWD sudo access after all
