seven1m/onebody

- spec/controllers/accounts_controller_spec.rb
Correct failing test where the order was causing issues within tests for the session when matching more than one family member
> Order of people is not important when testing session

- Gemfile
- Gemfile.lock
- app/jobs/message_send_job.rb
- app/models/message.rb
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
Uses [sucker_punch](https://github.com/brandonhilkert/sucker_punch) for job queueing, which does not require a separate running worker process.
This finished #200 and gets a good start on #212 for other background jobs.
> Send email in background

- app/assets/javascripts/app/maps.js.coffee
- app/helpers/administration/settings_helper.rb
- app/helpers/maps_helper.rb
- app/views/administration/settings/index.html.haml
- config/locales/en/admin.yml
- config/settings.yml
In the UK I find a more zoomed in map more helpful. Therefore I've added a setting to allow this to be set per site.
Apologies for the multiple commits - few problems in my git workflow when working on multiple features :disappointed:
> Add setting to allow zoom level of maps diplayed on site to be altered

- app/assets/javascripts/app/search.js.coffee
- app/models/search.rb
- app/views/searches/create.html.haml
- config/locales/en/search.yml
- spec/models/search_spec.rb
I'm working on a feature to be able to search for people who belong to/don't belong to a group in a particular category. Example use case: we want to see as many as possible in fellowship groups - search for all those not in groups who have a "fellowship" category. Would any of you mind having a quick look to see what you think? 
I'm not sure in particular about my use of the code 
```ruby
@scope = Person.eager_load(:family, :groups)
```
[line in code here](https://github.com/aunderwo/onebody/blob/dc988b3baf634df0aa0a65387f7661a937f5df37/app/models/search.rb#L28). I'm implementing this in order to force a LEFT OUTER JOIN so that I include people not in any groups. Comments much appreciated. Thanks
> DONT' MERGE search by membership of group category

- config/environments/production.rb
* Removes manual manipulation of Rack middleware in favor of standard Rails config settings
* Adds new environment variable setting `SENDFILE_HEADER` for people using nginx (see #375)
> Clean up production config for SERVE_ASSETS=true

- app/assets/stylesheets/application.css.scss
- app/helpers/people_helper.rb
- app/views/people/_details.haml
- config/locales/en/people.yml
Admins can see more details if they have the "View Hidden Properties" privilege. This lock icon will give them a clue why they are seeing this info.
This is to clarify #378.
> Show lock with tooltip on profile items that are hidden

- app/models/message.rb
Use `errors.full_messages.each` instead
> `errors.each_full` is deprecated

- app/models/search.rb
The Search sorting test fails using postgres due to case sensitivity. This change introduces LOWER(), which I think is standard SQL across databases, in order to ensure that sorting works as expected for the existing test.
Signed-off-by: Tim Mecklem <timothy@mecklem.com>
> Convert Search SQL to use case insensitive sorting

- Vagrantfile
Provisioning breaks at the moment because `rake` does not exist in the current expected location (`/home/vagrant/.rvm/gems/#{$ruby_version}@onebody/bin/rake`).
At this point in the provisioning process, we are already `cd`'ed into `/vagrant` and bundler has just finished installing the gems, so it's safe to just run `rake` to create the db, set it up and seed it.
I was able to provision a brand new VM all the way through after these changes, but it would be nice for another dev to try it as well. :wink:
> Vagrantfile updates to provision successfully all the way through.

- app/models/setup.rb
- spec/models/setup_spec.rb
Adds Setup spec to verify Person attributes get set and feedback is given for blank domain. Fixes #495
> 495 No feedback for domain validation

- .travis.yml
Since ruby 2.2.3 is the latest patch I removed the specific version to ensure that it always checks against the latest patch version
> removing specific patch version

- app/assets/stylesheets/application.scss
This fixes #548 Missing icon on new message "Choose file" button
> Include bootstrap-sprockets in application stylesheets.

- app/assets/javascripts/app/documents.js.coffee
- app/controllers/documents_controller.rb
- app/views/documents/_form.haml
- app/views/documents/index.html.haml
- config/locales/en/documents.yml
- config/locales/en/general.yml
- spec/controllers/documents_controller_spec.rb
This branch supports multi document uploads. User presses upload multiple files and is prompted with a tabular screen where you can choose multiple files and specify names and descriptions, as defined in #523 
All Unit tests seemed to pass. I could add more (with a little guidance). All feedback is appreciated.
> Multidocument uploads

- CONDUCT.md
- README.md
This should go without saying, but I want to spell out that we are friendly and loving towards all who wish to contribute to this project (and other Church.IO projects). Contributions are judged according to their usefulness to churches -- not by the contributor.
> Add code of conduct to project

- config/initializers/pluralization.rb
- config/locales/plurals.rb
The solution was found at http://stackoverflow.com/questions/6166064/i18n-pluralization
The plurals table comes from
https://github.com/svenfuchs/i18n/blob/master/test/test_data/locales/plurals.rb
I've added only the languages currently supported in the project, and commented 'ro','ru'.
They could be enabled once the necessary 'few' (or 'many') keys are present in the yml files.
> Added support for 'few' pluralization form.

- app/models/import_parser/strategies/csv.rb
Otherwise UTF characters are ignored on import
This is the change proposed by @gustavobim  (see  https://github.com/churchio/onebody/issues/615)
Works for me, I hope it does not break anything....
> Force UTF encoding while importing strings

- app/helpers/albums_helper.rb
Hello.
Looks like there was another control flow operator (or) in file app/helpers/albums_helper.rb.
To mitigate the bug risk, I replaced it with boolean operator ||.
Thank you.
> Replaced control flow operator with boolean operator

- README.md
I was just running through the install procedure for Windows for fun (I've never run a Rails app on it before), and noticed that a link was broken. The old version was returning a 404.
BTW, very nice work on OneBody. I'm poking around the source right now, and I like what's here. Thanks!
> Update ImageMagick link for Windows install

- app/helpers/groups_helper.rb
Hello.
Looks like there were more control flow operators (and + not) in file app/helpers/groups_helper.rb.
To mitigate the bug risk, I replaced them with boolean operators && and !.
Thank you.
> Replaced control flow operators with boolean operators

- app/models/concerns/import/attributes.rb
- spec/models/import_execution_spec.rb
> Invalid birthdates should be set to nil rather than raise exceptions
